# Generated by Django 4.1.7 on 2023-04-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='unit_price',
        ),
    ]
