# Generated by Django 4.1.7 on 2023-04-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_last_name_customer_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
